import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1740817258145 implements MigrationInterface {
    name = 'Init1740817258145'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "varient_value" ("varientId" uuid NOT NULL, "valueAttrId" uuid NOT NULL, CONSTRAINT "PK_1878339849585ece16f0aac2a82" PRIMARY KEY ("varientId", "valueAttrId"))`);
        await queryRunner.query(`CREATE TABLE "category" ("name" character varying NOT NULL, CONSTRAINT "PK_23c05c292c439d77b0de816b500" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE TABLE "tag" ("name" character varying NOT NULL, CONSTRAINT "PK_6a9775008add570dc3e5a0bab7b" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE TABLE "brand" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "imageId" uuid, CONSTRAINT "UQ_5f468ae5696f07da025138e38f7" UNIQUE ("name"), CONSTRAINT "REL_062524ac7f03786e461134ea62" UNIQUE ("imageId"), CONSTRAINT "PK_a5d20765ddd942eb5de4eee2d7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attr_product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "productId" uuid NOT NULL, "hasImage" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_493831bf0db5de786080f58447d" UNIQUE ("name", "productId"), CONSTRAINT "PK_3d235b9621e6d4d6f50df2d6ddb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "value_attr" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "value" character varying NOT NULL, "imageId" uuid, "attrProductId" uuid NOT NULL, CONSTRAINT "UQ_566713624ec59b3e5c99ea2a8e2" UNIQUE ("value", "attrProductId"), CONSTRAINT "REL_9f33dd4f8e5bdd4c7c531b6c7b" UNIQUE ("imageId"), CONSTRAINT "PK_d83efbf51ca2fa207b34091e2af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "varient" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "productId" uuid NOT NULL, "pieceAvail" integer NOT NULL DEFAULT '0', "sold" integer NOT NULL DEFAULT '0', "price" numeric(10,2) NOT NULL, "discountPrice" numeric(10,2), CONSTRAINT "PK_3e040a720eab102a27c7e8948d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "favorite_detail" ("userId" uuid NOT NULL, "productId" uuid NOT NULL, "createAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_29e2af242316e4a17b67bcf079c" PRIMARY KEY ("userId", "productId"))`);
        await queryRunner.query(`CREATE TABLE "product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "starRating" numeric(2,1) NOT NULL DEFAULT '5', "reviewNumber" integer NOT NULL DEFAULT '0', "sold" integer NOT NULL DEFAULT '0', "pieceAvail" integer NOT NULL DEFAULT '0', "price" numeric(10,2) NOT NULL, "discountPrice" numeric(10,2), "categoryName" character varying NOT NULL, "brandId" uuid, "userId" uuid NOT NULL, CONSTRAINT "UQ_22cc43e9a74d7498546e9a63e77" UNIQUE ("name"), CONSTRAINT "CHK_a0dca3a29b4270fb1c92ab4aae" CHECK ("pieceAvail" >= 0), CONSTRAINT "CHK_251f085141bd156a7157afc002" CHECK ("sold" >= 0), CONSTRAINT "CHK_3ae45e9af822b48e31dfdf6edf" CHECK ("starRating" >=0 AND "starRating" <=5), CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "image" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "url" character varying NOT NULL, "key" character varying NOT NULL, "productId" uuid, CONSTRAINT "PK_d6db1ab4ee9ad9dbe86c64e4cc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_authby_enum" AS ENUM('GOOGLE', 'GITHUB', 'FACEBOOK', 'LOCAL')`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('ADMIN', 'USER')`);
        await queryRunner.query(`CREATE TYPE "public"."user_gender_enum" AS ENUM('MALE', 'FEMALE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying, "username" character varying, "phoneNumber" character varying, "password" character varying, "email" character varying NOT NULL, "currentHashedRefreshToken" character varying, "authBy" "public"."user_authby_enum" NOT NULL DEFAULT 'LOCAL', "role" "public"."user_role_enum" NOT NULL DEFAULT 'USER', "gender" "public"."user_gender_enum", "birthday" date, "avatarId" uuid, "code" character varying, "codeExprired" TIMESTAMP, CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "REL_58f5c71eaab331645112cf8cfa" UNIQUE ("avatarId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commune" ("id" character varying NOT NULL, "name" character varying NOT NULL, "districtId" character varying NOT NULL, CONSTRAINT "PK_bc512eb8412b43c9dc6e2c9e683" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "district" ("id" character varying NOT NULL, "name" character varying NOT NULL, "provinceId" character varying NOT NULL, CONSTRAINT "PK_ee5cb6fd5223164bb87ea693f1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "province" ("id" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_4f461cb46f57e806516b7073659" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "email" character varying NOT NULL, "orderId" uuid, "fullName" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "provinceId" character varying NOT NULL, "districtId" character varying NOT NULL, "communeId" character varying NOT NULL, "street" character varying NOT NULL, CONSTRAINT "REL_d25f1ea79e282cc8a42bd616aa" UNIQUE ("userId"), CONSTRAINT "REL_69d6c6a7d5b8e073488cf971f6" UNIQUE ("orderId"), CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "orderId" uuid NOT NULL, "varientId" uuid NOT NULL, "price" numeric(10,2) NOT NULL, "quantity" integer NOT NULL, CONSTRAINT "CHK_805e552e196a6b601ce77d042d" CHECK ("quantity" > 0), CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum" AS ENUM('pending', 'complete', 'cancel', 'shipping')`);
        await queryRunner.query(`CREATE TABLE "order" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "totalOrder" jsonb NOT NULL, "status" "public"."order_status_enum" NOT NULL DEFAULT 'pending', CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cart_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createAt" TIMESTAMP NOT NULL DEFAULT now(), "updateAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "varientId" uuid NOT NULL, "quantity" integer NOT NULL, CONSTRAINT "UQ_a800a4ab5b28938ea0d7646a489" UNIQUE ("userId", "varientId"), CONSTRAINT "CHK_762f7fe49b649072501fa9e2ec" CHECK ("quantity" >= 1), CONSTRAINT "PK_bd94725aa84f8cf37632bcde997" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_tag" ("productId" uuid NOT NULL, "tagName" character varying NOT NULL, CONSTRAINT "PK_903d9cb134149656fe391188a05" PRIMARY KEY ("productId", "tagName"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fd22d97428d2b0c25be95fb356" ON "product_tag" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_be7e39b01493cea5fb90b1ef7d" ON "product_tag" ("tagName") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab2ab5f5b8eacede125b0b157e" ON "varient_value" ("varientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0aaf15f24606ca542c2b6a4a5b" ON "varient_value" ("valueAttrId") `);
        await queryRunner.query(`ALTER TABLE "brand" ADD CONSTRAINT "FK_062524ac7f03786e461134ea624" FOREIGN KEY ("imageId") REFERENCES "image"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attr_product" ADD CONSTRAINT "FK_90689b65776c367269ffbcf4466" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "value_attr" ADD CONSTRAINT "FK_9f33dd4f8e5bdd4c7c531b6c7b1" FOREIGN KEY ("imageId") REFERENCES "image"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "value_attr" ADD CONSTRAINT "FK_cb5a64f2e2ff701dfee25a031fd" FOREIGN KEY ("attrProductId") REFERENCES "attr_product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "varient" ADD CONSTRAINT "FK_24ad75e2bad026a642a1cd5b4dc" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorite_detail" ADD CONSTRAINT "FK_3d8a86ae2f76646048711f56f7d" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "favorite_detail" ADD CONSTRAINT "FK_494513cdcca6fff56e33ecb4ca8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_3feda63c129805f4cbb907b3f6c" FOREIGN KEY ("categoryName") REFERENCES "category"("name") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_bb7d3d9dc1fae40293795ae39d6" FOREIGN KEY ("brandId") REFERENCES "brand"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_329b8ae12068b23da547d3b4798" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_c6eb61588205e25a848ba6105cd" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_58f5c71eaab331645112cf8cfa5" FOREIGN KEY ("avatarId") REFERENCES "image"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commune" ADD CONSTRAINT "FK_3ddcfc19466ec9e9ef415b96b55" FOREIGN KEY ("districtId") REFERENCES "district"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "district" ADD CONSTRAINT "FK_23a21b38208367a242b1dd3a424" FOREIGN KEY ("provinceId") REFERENCES "province"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_6b08d352c02976faa2b4b2933c3" FOREIGN KEY ("provinceId") REFERENCES "province"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_89e09cf52a27eec4a04378bbdda" FOREIGN KEY ("districtId") REFERENCES "district"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_ccd39de5b9edb3259ae4b58fbbf" FOREIGN KEY ("communeId") REFERENCES "commune"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_d25f1ea79e282cc8a42bd616aa3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_69d6c6a7d5b8e073488cf971f67" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_b3402e19169a12adf30a4d9a713" FOREIGN KEY ("varientId") REFERENCES "varient"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_caabe91507b3379c7ba73637b84" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_item" ADD CONSTRAINT "FK_158f0325ccf7f68a5b395fa2f6a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_item" ADD CONSTRAINT "FK_6ef5bc6863743d94558fbaaabe6" FOREIGN KEY ("varientId") REFERENCES "varient"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "varient_value" ADD CONSTRAINT "FK_ab2ab5f5b8eacede125b0b157eb" FOREIGN KEY ("varientId") REFERENCES "varient"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "varient_value" ADD CONSTRAINT "FK_0aaf15f24606ca542c2b6a4a5b5" FOREIGN KEY ("valueAttrId") REFERENCES "value_attr"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_tag" ADD CONSTRAINT "FK_fd22d97428d2b0c25be95fb3567" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_tag" ADD CONSTRAINT "FK_be7e39b01493cea5fb90b1ef7d3" FOREIGN KEY ("tagName") REFERENCES "tag"("name") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_tag" DROP CONSTRAINT "FK_be7e39b01493cea5fb90b1ef7d3"`);
        await queryRunner.query(`ALTER TABLE "product_tag" DROP CONSTRAINT "FK_fd22d97428d2b0c25be95fb3567"`);
        await queryRunner.query(`ALTER TABLE "varient_value" DROP CONSTRAINT "FK_0aaf15f24606ca542c2b6a4a5b5"`);
        await queryRunner.query(`ALTER TABLE "varient_value" DROP CONSTRAINT "FK_ab2ab5f5b8eacede125b0b157eb"`);
        await queryRunner.query(`ALTER TABLE "cart_item" DROP CONSTRAINT "FK_6ef5bc6863743d94558fbaaabe6"`);
        await queryRunner.query(`ALTER TABLE "cart_item" DROP CONSTRAINT "FK_158f0325ccf7f68a5b395fa2f6a"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_caabe91507b3379c7ba73637b84"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_b3402e19169a12adf30a4d9a713"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_69d6c6a7d5b8e073488cf971f67"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_d25f1ea79e282cc8a42bd616aa3"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_ccd39de5b9edb3259ae4b58fbbf"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_89e09cf52a27eec4a04378bbdda"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_6b08d352c02976faa2b4b2933c3"`);
        await queryRunner.query(`ALTER TABLE "district" DROP CONSTRAINT "FK_23a21b38208367a242b1dd3a424"`);
        await queryRunner.query(`ALTER TABLE "commune" DROP CONSTRAINT "FK_3ddcfc19466ec9e9ef415b96b55"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_58f5c71eaab331645112cf8cfa5"`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_c6eb61588205e25a848ba6105cd"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_329b8ae12068b23da547d3b4798"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_bb7d3d9dc1fae40293795ae39d6"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_3feda63c129805f4cbb907b3f6c"`);
        await queryRunner.query(`ALTER TABLE "favorite_detail" DROP CONSTRAINT "FK_494513cdcca6fff56e33ecb4ca8"`);
        await queryRunner.query(`ALTER TABLE "favorite_detail" DROP CONSTRAINT "FK_3d8a86ae2f76646048711f56f7d"`);
        await queryRunner.query(`ALTER TABLE "varient" DROP CONSTRAINT "FK_24ad75e2bad026a642a1cd5b4dc"`);
        await queryRunner.query(`ALTER TABLE "value_attr" DROP CONSTRAINT "FK_cb5a64f2e2ff701dfee25a031fd"`);
        await queryRunner.query(`ALTER TABLE "value_attr" DROP CONSTRAINT "FK_9f33dd4f8e5bdd4c7c531b6c7b1"`);
        await queryRunner.query(`ALTER TABLE "attr_product" DROP CONSTRAINT "FK_90689b65776c367269ffbcf4466"`);
        await queryRunner.query(`ALTER TABLE "brand" DROP CONSTRAINT "FK_062524ac7f03786e461134ea624"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0aaf15f24606ca542c2b6a4a5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab2ab5f5b8eacede125b0b157e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be7e39b01493cea5fb90b1ef7d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd22d97428d2b0c25be95fb356"`);
        await queryRunner.query(`DROP TABLE "product_tag"`);
        await queryRunner.query(`DROP TABLE "cart_item"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`DROP TABLE "province"`);
        await queryRunner.query(`DROP TABLE "district"`);
        await queryRunner.query(`DROP TABLE "commune"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_authby_enum"`);
        await queryRunner.query(`DROP TABLE "image"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "favorite_detail"`);
        await queryRunner.query(`DROP TABLE "varient"`);
        await queryRunner.query(`DROP TABLE "value_attr"`);
        await queryRunner.query(`DROP TABLE "attr_product"`);
        await queryRunner.query(`DROP TABLE "brand"`);
        await queryRunner.query(`DROP TABLE "tag"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "varient_value"`);
    }

}
